name: Deploy via SSH
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "ssh successful"
          # git update to latest codebase on main branch
          echo "Beginning CI"
          cd ~/sports-calendar-scraper && git pull
          echo "Latest code pulled to server"
          npm install
          echo "Installed new node packages"
          echo ${{ secrets.SUDO_PASS }} | sudo -S cp runsportscalcraper.sh /usr/bin
          echo "Scraper executable updated on server"
          echo "CI completed"
     