name: Raspberry Pi CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the development branch
  push: 
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   # This workflow contains a single job called "update-rpi"
  update-rpi:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Load .env file 
      uses: falti/dotenv-action@v0.2.7

    # - name: Update .env file secret
    #   uses: gliech/create-github-secret-action@v1
    #   with:
    #     name: NODE_ENVIRONMENT_VARIABLES
    #     value:  ${{ steps.dotenv.outputs }}
    #     pa_token: ${{ secrets.PAT }}

    - name: Deploy via SSH
      uses: fifsky/ssh-action@master
      with:
        command: |
          echo ssh successful

          cd ~/sports-calendar-scraper
          echo starting CI
          
          echo ${{ steps.dotenv.ouputs }} > .env
          echo Updated environment variables with .env

          git pull
          echo pulled latest code to server

          echo ${{ secrets.PASSWORD }} | sudo -S cp runsportscalscraper.sh /usr/bin
          echo Updated scraper executable on server

          npm install
          echo Updated npm packages
          
          echo CI completed
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
     