name: Deploy via SSH
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: fifsky/ssh-action@master
      with:
        command: |
          echo ssh successful
          # git update to latest codebase on main branch
          echo Starting CI
          cd ~/sports-calendar-scraper && git pull
          echo Latest code pulled to server
          npm install
          echo Updated npm packages
          echo ${{ secrets.SUDO_PASS }} | sudo -S cp runsportscalcraper.sh /usr/bin
          echo Updated craper executable on server
          echo Sports calendar scraper has been updated
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
     